### ISSUE TITLE
Question: AEM Site Creation Wizard not offering option to import file

### ISSUE THREAD

**Issue by vhochstein** [adobe/aem-site-template-standard#68]
### Expected Behaviour
AEM Sites Creation Wizard should offer option to import a file.

### Actual Behaviour
AEM Sites Creation Wizard does not offer option to import a file

#### Steps to Reproduce
Go to Sites
Click Create -> Site

No option to Import a file is offered:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/109388/140469479-5695f9f0-5828-40a0-a86d-cf52d83e0df7.png">

#### Platform and Version
2021.10.5977.20211021T153528Z

**Comment by gabrielwalt** [comment]
Hi @vhochstein,

The option in your screenshot is the old site creation wizard that was using site blueprints, not site templates.
To use the site templates, you must choose a different option below the "Create" button that is named "Site from template".
This option was still hidden behind a feature toggle in November, but has been made public with the December release of Cloud Service.
Make sure to update your Cloud Service environment, and you should then see this new "Create > Site from template" option, which will allow you to import a site template file.

Best,
Gabriel
