### ISSUE TITLE
Experience Fragment Editor and Preview don't load fonts/images from /theme/src/resources

### ISSUE THREAD

**Issue by jzeltman** [adobe/aem-site-template-standard#74]
![image](https://user-images.githubusercontent.com/200346/148265100-5e9a659a-20cd-4085-b95d-2c1fb53b6290.png)

In the Experience Fragment Editor, and in View as Published, something is preventing the images and fonts loaded from /theme/src/resources. It appears the fonts are trying to load from `src: url(../src/resources/fonts/SourceSansPro/SourceSansPro-Black..ttf)` which works fine when viewing normal content pages, but not when in an Experience Fragment.

### Expected Behaviour
Fonts/Images from /theme/resources load as expected in XFs.

### Actual Behaviour
Fonts/Images don't load

### Reproduce Scenario (including but not limited to)
1. Create site from template.
2. Navigate to header experience fragment
  - Visit http://localhost:4502/editor.html/content/adobe-wireframe-111/en/home.html
  - http://localhost:4502/content/adobe-wireframe-111/en/home.html?wcmmode=disabled
3. See the serif fonts instead of the expected sans-serif Adobe font

#### Steps to Reproduce
1. Create site from template.
2. Navigate to header experience fragment
  - Visit http://localhost:4502/editor.html/content/adobe-wireframe-111/en/home.html
  - http://localhost:4502/content/adobe-wireframe-111/en/home.html?wcmmode=disabled
3. See the serif fonts instead of the expected sans-serif Adobe font
4.

**Comment by vladbailescu** [comment]
I no longer see this issue with the latest template/theme versions and builders.
