### ISSUE TITLE
Some Core Components display as work in progress and/or v3 in the page editor

### ISSUE THREAD

**Issue by kristienkellens** [adobe/aem-site-template-standard#88]
See screenshot:
<img width="1035" alt="Screenshot 2022-03-30 at 08 35 18" src="https://user-images.githubusercontent.com/81566431/160775668-61d66de8-25b1-4a3c-badf-da57a74e9fdd.png">

**Steps to reproduce**

1.  Create site from template 
2.  Navigate to and edit the homepage
3. In Edit Mode, open the components tab in the left side-rail

**version**
latest version (Standard AEM Site Template 2.1.1)

**Comment by vladbailescu** [comment]
This should be fixed since https://github.com/adobe/aem-core-wcm-components/releases/tag/core.wcm.components.reactor-2.18.0
