### ISSUE TITLE
Logging into AEM Cloud using Sites30 Proxy 

### ISSUE THREAD

**Issue by charlievaughan** [adobe/aem-site-template-standard#89]
Hi guys

@bartoszglow  I'm having issues logging into a dev instance of AEM Cloud after running `npm run live` to test frontend changes.

Is there any documentation on permissions that need to be granted to a user or a special user profile that needs to be configured?

I can log into the AEM author as a Business Owner and have full admin rights using my Adobe ID.

If I try to sign in under `http://localhost:7002` using my Adobe ID I get redirected to the following URL which returns a 403:

`https://author-p63602-e526610.adobeaemcloud.com/callback/j_security_check?code=eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEta2V5LWF0LTEuY2VyIiwia2lkIjoiaW1zX25hMS1rZXktYXQtMSIsIml0dCI6ImF0In0.eyJpZCI6IjE2NTA2MzU0MDU0NTRfYzEwOWY5M2UtOWQ5ZC00MDVhLThhMjktMTM0NzUyYmYxMDUyX3VlMSIsInR5cGUiOiJhdXRob3JpemF0aW9uX2NvZGUiLCJjbGllbnRfaWQiOiJ3ZWItcDYzNjAyLWU1MjY2MTAtYzA2ODQyYjctZGU1Yy00MjgyLWI2MTUtYjFlMTk1NTE1NzhiIiwidXNlcl9pZCI6IjIyMkU1N0UwNjI0NUE4NzAwQTQ5NUM4Q0BBZG9iZUlEIiwic3RhdGUiOiI5YjdmbzlmOWcxYnFmbW9vZXF2bmNqamxiNSIsImFzIjoiaW1zLW5hMSIsImFhX2lkIjoiMjIyRTU3RTA2MjQ1QTg3MDBBNDk1QzhDQEFkb2JlSUQiLCJmZyI6IldNREI0WktPWFBNN0lQVUtHTVFGUkhRQU9BPT09PT09Iiwic2lkIjoiMTY1MDYzNTIzMDU3N182Mzc3MDY2ZC03OTc5LTQ1NDAtYmFlMi01NzZhNjE5NjgzOTRfdWUxIiwib3RvIjp0cnVlLCJleHBpcmVzX2luIjoiMTgwMDAwMCIsInNjb3BlIjoiQWRvYmVJRCxvcGVuaWQscmVhZF9vcmdhbml6YXRpb25zLGFkZGl0aW9uYWxfaW5mby5wcm9qZWN0ZWRQcm9kdWN0Q29udGV4dCIsImNyZWF0ZWRfYXQiOiIxNjUwNjM1NDA1NDU0In0.elTDUTTD9CME7fZv_NuxxECFeneGYCN3z08LUzkD152hyQ-jJZe_lKVMv18aEZ2BUPq4tzR3_KiOxgg4Glnx4UjEfdjtXAwocrtvWuONaUL75ejTC_St1qbJzYqwpP-8enAee13jKi76beqiesShqs43mxP_c4xpEkrOe3qmplXmzgTAr_YpTlim2v5Iq5BmkHJlJ3b_-uL4u6S_M40Qspfq6_28KrchYXLg6ocM7t0QYa57kwbPWJPA4afNC0HI9qbRA5ZAlTFM5RqOgWCDNeS6gyATFYHn2Bbnrm-pRvbcVxME1_xPJ_YFRrTOoSzsvjTRoBXMmrMy2RIXxfmfEA&state=9b7fo9f9g1bqfmooeqvncjjlb5`

But then if I navigate to `https://author-p63602-e526610.adobeaemcloud.com/aem/start.html` I'm logged in and have full access.

So this seems to be an issue with logging in under localhost.

This is basically a vanilla site created using the Standard AEM Site Template 2.1.1.

I've downloaded the Theme Sources from the AEM site and tested the theme code from this repository with the same result.

Regards, Charlie

**Comment by vladbailescu** [comment]
Unfortunately only AEM user/password authentication is supported by the preview/proxy. You will need to create a temporary user granting the needed access.
